sudo: required
services:
  - docker

before_install:
  - docker build -t juston/docker-react -f Dockerfile.dev .

script:
  - docker run juston/docker-react npm run ci_test -- --coverage

deploy:
  provider: elasticbeanstock
  region: "us-east-2"
  app: "docker-CI"
  env: "DockerCi-env"
  bucket_name: "elasticbeanstalk-us-east-2-452966561568"
  bucket_path: "docker-CI"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key:
    secure: $AWS_SECRET_KEY

